### PR TITLE
Remove need to sign CLA

### PR DESCRIPTION
**Pull request by RCheesley**
We no longer need developers to sign the CLA to contribute, so let's remove it from the onboarding docs! 🥳

### CODE REVIEW

**Review by IonutOjicaDE — CHANGES_REQUESTED** [review]
The links in the Table of contents should be also updated.

**Comment by RCheesley** [comment]
Yep I realised I missed it out and made a commit here: [403a67d](https://github.com/mautic/mautic-community-handbook/pull/154/commits/403a67d01a3e803a2c3ad67d5d08d8aa5a0f82fd)

**Review by daniellord32 — APPROVED** [review]
looks good, great work @RCheesley

**Comment by RCheesley** [comment]
Thanks folks!

**Comment by RCheesley** [comment]
@all-contributors add @IonutOjicaDE for review

**Comment by RCheesley** [comment]
@all-contributors add @daniellord32 for review

**Pull request merged**
