### PR TITLE
Added the overview & community council pages.

### PR DESCRIPTION
**Pull request by RitaOC**
This PR contains the community leadership coverted content in the community handbook.

### CODE REVIEW

**Comment by RitaOC** [comment]
Kindly Review @RCheesley @favour-chibueze @fakela

**Comment by RCheesley** [comment]
@RitaOC could you please check the heading underlines? They must always be the exact length of the heading that they are beneath.

Thanks!

**Comment by RitaOC** [comment]
> @RitaOC could you please check the heading underlines? They must always be the exact length of the heading that they are beneath.


Thanks so much @RCheesley, I've worked on it. 
Awaiting your review

**Review by RCheesley — APPROVED** [review]
This is GTG now the vale fixes are addressed. The linter is failing because it seems to be trying to lint the entire docs directory rather than just these changed files - not sure why but we will address in another PR.

**Comment by favour-chibueze** [comment]
Please, let's add @RitaOC to the contributors page. @RCheesley

**Comment by RCheesley** [comment]
@all-contributors please add @RitaOC for docs

**Pull request merged**
