### PR TITLE
update to the writers section

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Comment by fakela** [comment]
@RCheesley this prompted me to create another PR with your changes, is it okay

**Review by RCheesley — APPROVED** [review]
Awesome, thanks for jumping on it!

**Comment by fakela** [comment]
> Awesome, thanks for jumping on it!

Okay, i started a review but since this is approved here, then i don’t think that’s needed

**Review by RCheesley — APPROVED** [review]
Good to go! 🚀

**Pull request merged**
