### PR TITLE
Issue #192

### PR DESCRIPTION
**Pull request by vibhuti019**
### Also, I have changes the folder name to camel case

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Thanks for fixing the broken link! Please remove the image change, as that's not relevant to this PR - one PR for each issue. I don't think it's necessary to change the folder name, if it's working OK as is.

**Comment by vibhuti019** [comment]
@RCheesley Now there is just a single change. Please review,

**Review by RCheesley — APPROVED** [review]
Awesome, thanks for the fix @vibhuti019 🚀

**Comment by RCheesley** [comment]
@all-contributors please add @vibhuti019 for docs

**Pull request merged**
